### ISSUE TITLE
Hyperion does not build on Solaris 11

### ISSUE THREAD

**Issue by racingmars** [SDL-Hercules-390/hyperion#406]
## Hyperion Solaris build support

Hyperion does not build on Solaris 11 on SPARC (and I'm guessing all but one of these might be a problem on Solaris on x86_64 as well). I have documented all the changes I needed to make here, but I don't know enough about autoconf to submit a patch to handle most of these things the "right way." I'm hoping someone with more knowledge in that area can split these into "just make the change to the source" versus "update the autoconf stuff to handle this."

### 1. Configure script incorrectly decides the platform is 32 bit, not 64 bit.

The build tries to link against the 32-bit versions of the extpkgs (e.g. libcrypto32.a instead of libcrypto64.a). Looking in the configure script, it's obvious why:

```
#----------------------------------------------------#
#  Determine target CPU bitness  (32-bit or 64-bit)  #
#----------------------------------------------------#

{ $as_echo "$as_me:${as_lineno-$LINENO}: checking target CPU bitness " >&5
$as_echo_n "checking target CPU bitness ... " >&6; }

case "$target_cpu" in

    *64|*64le)
        hc_cv_cpu_bits=64
        ;;
    *)
        hc_cv_cpu_bits=32
        ;;
esac
```

On this platform, $target_cpu is getting set to "sparc", which doesn't end in 64. I correct this problem by modifying the configure script, changing `*64|*64le)` to `*64|*64le|sparc)`.

### 2. In crypto.c we try to use the Windows code.

This is due to correct random method not being selected in hcrypto.h.

The arc4random_buf() API is available on Solaris, so in hcrypto.h I changed:

```
#elif defined( BSD )

  #define USE_ARC4RANDOM            // (use 'arc4random_buf()' API)
```

to

```
#elif defined( BSD ) || defined( __sun__ )

  #define USE_ARC4RANDOM            // (use 'arc4random_buf()' API)
```

(`__sun__` is set by GCC; I'm not sure if there is a more appropriate macro to use here that autoconf sets.)

/dev/urandom is also available on Solaris, but I haven't verified if those ioctl values in hcrypto.h would work, so I just went with the easy route of using arc4random_buf().

### 3. The `regex` variable in panel.c conflicts with the regex() function provided by libgen.h on some platforms.

Line 1687 of panel.c declares a variable named "regex". However, panel.c also includes <libgen.h> by way of hstdinc.h. Pre-XPG6, libgen.h defined regcmp() and regex(). Through feature macros (e.g. _XOPEN_SOURCE=600) the Solaris headers will exclude those functions, however it also ends up excluding other legacy functions and definitions which the Hyperion code _does_ depend on.

The easiest way to solve this problem was to avoid the conflict; I renamed the variable `regex` to `regexp` (lines 1687, 1693, 1706).

### 4. Incorrect ifreq structure assumption in hifr.h.

On Solaris, the ifreq struct matches that of BSD, not Linux. At hifr.h line 113, I changed:

```
#if defined( __APPLE__ ) || defined( FREEBSD_OR_NETBSD )
  #define  hifr_name       ifreq.ifr_name
#else
  #define  hifr_name       ifreq.ifr_ifrn.ifrn_name
#endif
```

to

```
#if defined( __APPLE__ ) || defined( FREEBSD_OR_NETBSD ) || defined( __sun__ )
  #define  hifr_name       ifreq.ifr_name
#else
  #define  hifr_name       ifreq.ifr_ifrn.ifrn_name
#endif
```

### 5. tcpip.c needs to include <sys/filio.h>

To get the definitions of `FIONBIO` and `FIONREAD`, I had to add `#include <sys/fileio.h>` to tcpip.c.

### 6. ctc_ptp.c needs to include <sys/sockio.h>

To get the definition of `SIOCGIFMTU`, I had to add `#include <sys/sockio.h>` to ctc_ptp.c.

### 7. IPv6 problems

I don't need IPv6 support, so I just configure with `--disable-ipv6`.

### Successful build

After the above changes, with the appropriate prerequisites installed, extpkgs built, and the GNU versions of tools (grep, egrep, m4, sed, etc.) on my PATH ahead of the Solaris POSIX-compliant versions, Hyperion successfully builds (and the resulting binary IPLs my MVS 3.8J system) with:

`./configure --prefix=/opt/sdlhyperion --disable-ipv6 --enable-extpkgs=/export/home/mwilson/hyperion-bld/extpkgs`
`make`
`make install`

**Comment by wrljet** [comment]
Matthew,

> 
> ## 1. Configure script incorrectly decides the platform is 32 bit, not 64 bit.
> 
> The build tries to link against the 32-bit versions of the extpkgs (e.g. libcrypto32.a instead of libcrypto64.a). Looking in the configure script, it's obvious why:
> 
> ```
> #----------------------------------------------------#
> #  Determine target CPU bitness  (32-bit or 64-bit)  #
> #----------------------------------------------------#
> 
> { $as_echo "$as_me:${as_lineno-$LINENO}: checking target CPU bitness " >&5
> $as_echo_n "checking target CPU bitness ... " >&6; }
> 
> case "$target_cpu" in
> 
>     *64|*64le)
>         hc_cv_cpu_bits=64
>         ;;
>     *)
>         hc_cv_cpu_bits=32
>         ;;
> esac
> ```
> 
> On this platform, $target_cpu is getting set to "sparc", which doesn't end in 64. I correct this problem by modifying the configure script, changing `*64|*64le)` to `*64|*64le|sparc)`.

Could you run `git rev-parse --short HEAD` so we know what version of the sources you're working with.

Run `hyperion/autoconf/config.guess` and report its output here.

Thanks,
Bill

**Comment by racingmars** [comment]
Hi Bill,

> Could you run `git rev-parse --short HEAD` so we know what version of the sources you're working with.

b8a26cfd
 
> Run `hyperion/autoconf/config.guess` and report its output here.

sparc-sun-solaris2.11

**Comment by wrljet** [comment]
Matthew,

`config.guess` doesn't seem to be aware of any 64-bit Sparc running Solaris.
(and we have a quite recent version of it)

I suggest you try running (the unmodified) `configure` with these options and see what happens:

`--build=sparc64-sun-solaris2.11 --target=sparc64-sun-solaris2.11`

And it would not hurt to run `autogen.sh` first, as well.

Bill

**Comment by racingmars** [comment]
Hi Bill,

> `config.guess` doesn't seem to be aware of any 64-bit Sparc running Solaris.
> (and we have a quite recent version of it)

A bit odd, since every Sparc processor since 1995 has been 64-bit. I'm a bit surprised it's just picking up "sparc" and not "sparcv9", though. If anything sparcv9 is what I'd expect to distinguish from pre-1995 32-bit sparc, but that would still fail the "*64" check.

> I suggest you try running (the unmodified) `configure` with these options and see what happens:
> `--build=sparc64-sun-solaris2.11 --target=sparc64-sun-solaris2.11`

This does work to get around this particular problem.

However, I suspect this shouldn't be necessary. It may be a convention on Linux that the cpu name should have 64 in it if it's 64-bit, but that doesn't seem to hold on other platforms.

For example, I've also been working on building on AIX on POWER. We run into the same problem: config.guess reports "powerpc-ibm-aix7.2.5.0", and the build tries to link against the 32-bit versions of the extpkgs due to that configure check.

But, configure / the build system clearly knows it's building for a 64-bit platform, despite the target being powerpc-ibm-aix7.2.5.0, because it's including the proper flags to GCC ("-maix64") and ld/ar (-X64) to produce a 64-bit build.

GCC on Solaris builds 64-bit output by default, so we can't directly see that the build system "knows" it's building for 64-bit by inferring its knowledge from compiler flags like we can on AIX, but I suspect it does know.

When using the vendor-provided GCC, with `gcc -dumpmachine` I get "sparcv9-solaris2.11" and "powerpc-ibm-aix7.2.0.0".

> And it would not hurt to run `autogen.sh` first, as well.

Yep, I've been doing that.

Thanks,
Matthew

**Comment by Fish-Git** [comment]
Bill (@wrljet),

I have items #<span>2</span> through #<span>6</span> queued and ready to commit if you'd like me to do that, leaving you to concentrate on just item #<span>1</span>. Would you like me to go ahead and commit them?

**Comment by wrljet** [comment]
Fish,

> 
> 
> Bill (@wrljet),
> 
> I have items #2 through #6 queued and ready to commit if you'd like me to do that, leaving you to concentrate on just item #1. Would you like me to go ahead and commit them?

Sounds good!

One (well, two) questions though.  Are items #5 and #6 safe on non-Solaris?

Bill

**Comment by Fish-Git** [comment]
> Sounds good!

Done!

> Are items #5 and #6 safe on non-Solaris?

Dunno. But right now I have them guarded with `#if defined( __sun__ )` so non-Solaris shouldn't be impacted.

(I hate introducing platform-specific tests in Hercules but I'm not quite sure how to code a platform-independent _**feature**_ test instead, so I took the Quick & Dirty lazy way out for now.)

**Comment by Fish-Git** [comment]
Matthew (@racingmars),

Due to other issues that have popped up recently, I sort of lost track of where we left off at with this issue of yours. If you do a re-clone of the current state of our repository (as of today), does Hercules now build okay for you on your Solaris 11 system? Is it okay to close this issue? Or is there still more work remaining?

Thanks.

**Comment by racingmars** [comment]
Hi Fish,

One problem remains, due to a typo on my part in my original bug report. Line 55 in tcpip.c should be `#include <sys/filio.h>` (not the full word `fileio.h`).

After fixing that, ab7f1a44 builds cleanly on Solaris SPARC (with `--build=sparc64-sun-solaris2.11 --target=sparc64-sun-solaris2.11` as suggested by Bill).

**Comment by Fish-Git** [comment]
> Line 55 in tcpip.c should be `#include <sys/filio.h>` (not the full word `fileio.h`).

Thanks. Fixed by commit 4bf2975df5e512bd5ffd5d2b5be85eea5516df0c.

Closing.
